src/renderer/components/common/SelectableSignatory/SelectableSignatory.tsx, src/renderer/screens/Operations/components/OperationFullInfo.tsx, src/renderer/screens/Operations/components/modals/ApproveTx.tsx, src/renderer/screens/Operations/components/modals/RejectTx.tsx, src/renderer/screens/Operations/components/modals/SignatorySelectModal.tsx, src/renderer/screens/Transfer/common/utils.tsx, src/renderer/screens/Transfer/components/ActionSteps/InitOperation.tsx, src/renderer/screens/Transfer/components/TransferForm.tsx
fix native token fee validation for approve/reject tx,  and multisig/multishard/simple transfer creation
https://app.clickup.com/t/85ztdckm5
=> Fix: native token fee validation

src/renderer/services/staking/eraService.ts
Reference implementation https://github.com/polkadot-js/apps/blob/1879a37f53e0a29de644b9420ef74bdb541f3210/packages/react-components/src/StakingUnbonding.tsx#L39
=> feat: improve unstaking countdown

src/renderer/components/ui-redesign/Dropdowns/Select/Select.tsx, src/renderer/screens/Staking/Operations/ChangeValidators/InitOperation/InitOperation.tsx, src/renderer/screens/Staking/Operations/Destination/InitOperation/InitOperation.tsx, src/renderer/screens/Staking/Operations/components/OperationForm/OperationForm.tsx, src/renderer/screens/Staking/Overview/components/NetworkInfo/NetworkInfo.test.tsx, src/renderer/screens/Staking/Overview/components/NetworkInfo/NetworkInfo.tsx, src/renderer/services/staking/eraService.ts, src/renderer/services/staking/stakingDataService.ts
- Removed fee validation for multisig staking (validators, destination)
- Validate deposit before fee
- Generic for dropdown
- Set new selected network of staking in localstorage (it was meant to work but got lost for whatever reason)
[Task](https://app.clickup.com/t/863g9y8nf)
=> Fix: Validation

src/renderer/components/common/SignatoryCard/SignatoryCard.tsx, src/renderer/screens/Operations/common/utils.ts, src/renderer/screens/Operations/components/Log.tsx, src/renderer/screens/Operations/components/OperationFullInfo.tsx, src/renderer/screens/Settings/Overview/components/Version/Version.tsx
Fixes:
- Changed signatory name source priority
- Added padding for version block on settings
=> Fix: changed signatory name source priority

src/renderer/screens/Staking/Operations/Unstake/InitOperation/InitOperation.tsx
- Fixed bad chill calculation
[Task](https://app.clickup.com/t/85zte8aw3)
=> Fix: Make correct chill

src/renderer/components/common/QrCode/QrGeneratorContainer/QrGeneratorContainer.tsx, src/renderer/components/common/QrCode/common/constants.ts
Link example https://metadata.novasama.io/?tab=1#/kusama
=> fix: metadata portal link leads to metadata page

src/renderer/screens/Operations/components/ActionSteps/Submit.tsx, src/renderer/screens/Operations/components/modals/RejectTx.tsx, src/renderer/screens/Staking/Operations/components/Submit/Submit.tsx
- Fixed close button for staking
[Task](https://app.clickup.com/t/861n020m6)
=> Fix: Close button

src/renderer/context/MatrixContext/MatrixContext.tsx, src/renderer/domain/account.ts, src/renderer/domain/transaction.ts
- More logging
- Leave room (reject invite) if not enough data or it's not valid
[Task](https://app.clickup.com/t/861mttq17)
=> Fix: Matrix join room handling

src/renderer/components/ui-redesign/Accordion/Accordion.tsx, src/renderer/components/ui-redesign/Popovers/MenuPopover/MenuPopover.tsx, src/renderer/screens/Assets/components/NetworkAssets/NetworkAssets.tsx, src/renderer/screens/Operations/components/Operation.tsx
- Fixed hover/focus effects on accordion
[Task_1](https://app.clickup.com/t/86787vvpq)
[Task_2](https://app.clickup.com/t/85ztexc6w)
=> Fix: Hover effects

src/renderer/components/modals/CreateMultisigAccount/CreateMultisigAccount.test.tsx, src/renderer/components/modals/CreateMultisigAccount/CreateMultisigAccount.tsx
- Use live contacts to get newly added ones
[Task](https://app.clickup.com/t/85zt9q9x5)
=> Fix: Live contacts

src/renderer/components/ui-redesign/Dropdowns/MultiSelect/MultiSelect.tsx, src/renderer/screens/Operations/components/Filters.tsx
Fixes:
- updated multiselect styles
- fixed operation filers jumping
=> fix: updated select style

src/renderer/screens/Assets/Assets.test.tsx, src/renderer/screens/Assets/Assets.tsx, src/renderer/screens/Assets/common/utils.ts, src/renderer/screens/Assets/components/NetworkAssets/NetworkAssets.tsx, src/renderer/services/balance/common/constants.ts, src/renderer/services/network/__tests__/chainsService.test.ts, src/renderer/services/network/chainsService.ts, src/renderer/services/network/common/types.ts, src/renderer/services/network/common/utils.ts, src/renderer/shared/utils/balance.ts, src/renderer/shared/utils/constants.ts
- Sort by groups according to [doc](https://docs.google.com/document/d/1_3esMRcmV3wrYwZrrM-0auycWwzMEnqA9DDyech74c8/edit#heading=h.kz34ra1ily4z)
[Task](https://app.clickup.com/t/2yt0dk7)
=> Fix: Chains sort by groups

package.json, pnpm-lock.yaml, src/renderer/components/ui-redesign/Animation/Animation.tsx
Lottie lib led to app stuck after displaying animation multiple time
=> Fix: changed lottie lib

src/renderer/screens/Operations/components/ActionSteps/Submit.tsx, src/renderer/screens/Operations/components/modals/ApproveTx.tsx
Fixes: 
- Two approves in a row fix ([task](https://app.clickup.com/t/85zteydrk))
- Removed watch only account form signatory modal
=> Fix: added onclose call after approve success

src/renderer/services/transaction/callDataDecoder.ts
=> fix: unknown transaction parsing

src/renderer/context/MatrixContext/MatrixContext.tsx, src/renderer/context/MultisigChainContext/MultisigChainContext.tsx, src/renderer/screens/Operations/Operations.tsx, src/renderer/screens/Operations/components/ActionSteps/Submit.tsx, src/renderer/screens/Operations/components/Log.tsx, src/renderer/screens/Operations/components/Operation.tsx, src/renderer/screens/Operations/components/OperationFullInfo.tsx, src/renderer/screens/Operations/components/modals/ApproveTx.tsx, src/renderer/screens/Staking/Operations/components/Submit/Submit.tsx, src/renderer/screens/Transfer/components/ActionSteps/Submit.tsx, src/renderer/services/multisigEvent/common/types.ts, src/renderer/services/multisigEvent/multisigEventService.ts, src/renderer/services/multisigTx/multisigTxService.ts
fix: event doubling
fix: race condition on throttling
fix: reset operations page on change txs
=> Fix: refactor events queue

src/shared/locale/en.json, src/shared/locale/ru.json
=> fix: add key for alertTitle

src/main/main.ts
Enterprise-like rolling file appender that allows to save logs with date in the name
=> feat: rolling log file appender

src/renderer/screens/Assets/components/Modals/ReceiveModal/ReceiveModal.test.tsx, src/renderer/screens/Assets/components/Modals/ReceiveModal/ReceiveModal.tsx
- Hide selector for non-multishard wallets
(Task)[https://app.clickup.com/t/861n40uaf]
=> Fix: Hide selector

src/renderer/components/common/QrCode/QrReader/QrReaderWrapper.tsx, src/renderer/screens/Staking/Operations/components/Signing/Signing.tsx, src/renderer/screens/Transfer/components/ActionSteps/Signing.tsx, src/shared/locale/en.json
fix: green border for success signing
=> fix: verification for single complex tx

src/renderer/features/contacts/ContactFilter/model/contact-filter.ts, src/renderer/features/contacts/ContactFilter/ui/ContactFilter.tsx, src/renderer/pages/AddressBook/Contacts/Contacts.tsx
- Use filtered contacts in address book
=> Fix: Effector filtered contacts

src/renderer/components/modals/CreateMultisigAccount/CreateMultisigAccount.test.tsx, src/renderer/components/modals/CreateMultisigAccount/CreateMultisigAccount.tsx
- Fixed subscription to contacts
=> Fix: Contacts subscription

src/renderer/features/assets/AssetRouteGuard/model/asset-guard.ts, src/renderer/features/assets/AssetRouteGuard/ui/AssetRouteGuard.tsx, src/renderer/features/contacts/EditRouteGuard/model/edit-guard.ts, src/renderer/features/contacts/EditRouteGuard/ui/EditRouteGuard.tsx
- Clear store on `unmount` or when `searchParams` change
=> Fix: Clear store contacts & assets

src/renderer/pages/Operations/common/utils.ts, src/renderer/pages/Operations/components/ActionSteps/Confirmation.tsx, src/renderer/pages/Operations/components/Details.tsx, src/renderer/pages/Operations/components/modals/ApproveTx.tsx, src/renderer/pages/Operations/components/modals/RejectTx.tsx, src/renderer/pages/Staking/Operations/Bond/Bond.tsx, src/renderer/pages/Staking/Operations/ChangeValidators/ChangeValidators.tsx, src/renderer/pages/Staking/Operations/Destination/Destination.tsx, src/renderer/pages/Staking/Operations/Redeem/Redeem.tsx, src/renderer/pages/Staking/Operations/Restake/Restake.tsx, src/renderer/pages/Staking/Operations/StakeMore/StakeMore.tsx, src/renderer/pages/Staking/Operations/Unstake/Unstake.tsx, src/renderer/widgets/SendAssetModal/ui/SendAssetModal.tsx, src/shared/locale/en.json, src/shared/locale/ru.json
- Added fields for `Approve/reject XCM`
- Minor styles fix
- Fixed modal title
=> Feat: Approve reject xcm

src/renderer/app/providers/context/GraphqlContext/GraphqlContext.test.tsx, src/renderer/app/providers/context/GraphqlContext/GraphqlContext.tsx, src/renderer/components/layout/PrimaryLayout/Navigation/Navigation.tsx, src/renderer/components/modals/CreateMultisigAccount/CreateMultisigAccount.test.tsx, src/renderer/entities/chain/ui/ChainTitle/ChainTitle.tsx, src/renderer/entities/multisig/lib/multisigTx/multisigTxService.ts, src/renderer/entities/network/lib/__tests__/chainsService.test.ts, src/renderer/entities/network/lib/chainsService.ts, src/renderer/entities/network/lib/index.ts, src/renderer/entities/network/lib/networkService.ts, src/renderer/features/assets/AssetRouteGuard/model/asset-guard.ts, src/renderer/features/operation/OperationsFilter/ui/OperationsFilter.tsx, src/renderer/pages/Assets/AssetsList/AssetsList.test.tsx, src/renderer/pages/Assets/AssetsList/AssetsList.tsx, src/renderer/pages/Assets/AssetsList/components/SelectShardModal/SelectShardModal.tsx, src/renderer/pages/Onboarding/Vault/ManageStep/ManageStep.tsx, src/renderer/pages/Onboarding/Vault/ManageStepSingle/ManageStepSingle.tsx, src/renderer/pages/Onboarding/WatchOnly/WatchOnly.tsx, src/renderer/pages/Operations/components/TransactionAmount.tsx, src/renderer/pages/Settings/Networks/Networks.tsx, src/renderer/pages/Staking/Overview/Overview.test.tsx, src/renderer/pages/Staking/Overview/components/NetworkInfo/NetworkInfo.test.tsx, src/renderer/pages/Staking/Overview/components/NetworkInfo/NetworkInfo.tsx, src/renderer/shared/api/xcm/xcmService.ts
- Fixed filtration for XCM operations
- Simplified `chainsService`
=> Fix: Xcm filter

src/renderer/pages/Operations/components/modals/RejectTx.tsx
- Fix RejectTx for WOW duplicates
=> Fix: Reject wow

src/renderer/shared/api/matrix/service/matrix.ts
- Removed room devices verification
=> Fix: Matrix room devices verification

src/main/main.ts
1. Keep 10 log files - may be discussed
2. Remove old files when new files is added
3. If the user already has more then 10 log files then extra-files will be removed
=> feat: remove old log files

src/renderer/app/App.tsx, src/renderer/entities/wallet/model/wallet-model.ts, src/renderer/features/contacts/ContactFilter/model/contact-filter.ts, src/renderer/features/currency/CurrencyForm/model/currency-form.ts, src/renderer/features/wallets/SelectWalletPairing/model/wallet-pairing-model.ts, src/renderer/features/wallets/WalletSelect/index.ts, src/renderer/features/wallets/WalletSelect/model/wallet-select-model.ts, src/renderer/features/wallets/WalletSelect/ui/WalletGroup.tsx, src/renderer/features/wallets/index.ts, src/renderer/widgets/CreateWallet/model/wallet-provider-model.ts, src/renderer/widgets/CreateWallet/ui/CreateWalletProvider.tsx, src/renderer/widgets/WalletDetails/index.ts, src/renderer/widgets/WalletDetails/model/wallet-provider-model.ts, src/renderer/widgets/WalletDetails/ui/WalletDetails.tsx, src/renderer/widgets/WalletDetails/ui/WalletDetailsProvider.tsx, tailwind.config.ts
- Wallet detail provider for future details
- Accounts are filtered inside provider's model
=> Feat: Wallet details setup

src/renderer/entities/operation/ui/SignButton.tsx, src/renderer/pages/Operations/components/ActionSteps/Confirmation.tsx, src/renderer/pages/Operations/components/modals/ApproveTx.tsx, src/renderer/pages/Operations/components/modals/RejectTx.tsx, src/renderer/widgets/SendAssetModal/ui/SendAssetModal.tsx, src/shared/locale/en.json, src/shared/locale/ru.json
- moved SignButton to confirm component
- fixed SignButton labels
=> fix: moved sign button to confirm component

src/renderer/pages/Operations/components/Details.tsx, src/renderer/pages/Operations/components/OperationCardDetails.tsx
- Fixed app crush on operations details page
=> Fix: operations page crush

src/renderer/app/App.tsx
Fixed redundant redirect on wallet change
=> Fix: No redirect

src/renderer/components/common/QrCode/QrGeneratorContainer/QrGeneratorContainer.tsx, src/renderer/components/common/Scanning/ScanSingleframeQr.tsx, src/renderer/entities/wallet/ui/cards/WalletCardSm/WalletCardSm.tsx, src/renderer/pages/Operations/common/utils.ts, src/renderer/pages/Operations/components/modals/ApproveTx.tsx, src/renderer/pages/Operations/components/modals/RejectTx.tsx, src/renderer/widgets/SendAssetModal/ui/SendAssetModal.tsx, src/shared/locale/en.json, src/shared/locale/ru.json
- signatory, title and padding updated
***
=> Feat: signing screen update

src/renderer/entities/signatory/ui/SelectableSignatory/SelectableSignatory.tsx, src/renderer/entities/signatory/ui/SignatoryCard/SignatoryCard.tsx, src/renderer/entities/wallet/lib/useAddressInfo.tsx, src/renderer/entities/wallet/ui/AddressWithExplorers/AddressWithExplorers.tsx, src/renderer/entities/wallet/ui/ContactItem/ContactItem.tsx, src/renderer/entities/wallet/ui/MultishardAccountsList/MultishardAccountsList.tsx, src/renderer/entities/wallet/ui/SelectableShard/SelectableShard.tsx, src/renderer/entities/wallet/ui/WalletRow/WalletRow.tsx, src/renderer/entities/wallet/ui/index.ts, src/renderer/shared/lib/hooks/index.ts, src/renderer/shared/lib/hooks/useModalClose.ts, src/renderer/widgets/WalletDetails/lib/types.ts, src/renderer/widgets/WalletDetails/model/wallet-provider-model.ts, src/renderer/widgets/WalletDetails/ui/MultishardWalletDetails.tsx, src/renderer/widgets/WalletDetails/ui/MultisigWalletDetails.tsx, src/renderer/widgets/WalletDetails/ui/WalletConnectDetails.tsx, src/renderer/widgets/WalletDetails/ui/WalletDetailsProvider.tsx, src/shared/locale/en.json, src/shared/locale/ru.json
=> Feat: Multishard details

src/renderer/entities/staking/lib/useValidatorsMap.ts, src/renderer/pages/Operations/components/OperationCardDetails.tsx
- check for staking pallet before getting validators
=> Fix: Operation details crush

src/renderer/assets/images/walletTypes/novaWallet.svg, src/renderer/entities/wallet/lib/wallet-utils.ts, src/renderer/pages/Operations/components/LogModal.tsx
- Fixed wallets filtering for lock screen
- Fixed nova wallet icon
=> Fix: wallet display on log screen

src/renderer/entities/signatory/index.ts, src/renderer/entities/signatory/lib/utils.ts, src/renderer/pages/Operations/components/OperationCardDetails.tsx, src/renderer/pages/Operations/components/OperationSignatories.tsx
- added `signatoryUtils` with `getSignatoryWallet`
- Fixed operation details field order and depositor wallet
=> Fix: operation signatories wallet and operation details order

src/renderer/features/wallets/SelectWalletPairing/ui/SelectWalletPairing.tsx, src/renderer/features/wallets/WalletSelect/ui/WalletGroup.tsx, src/renderer/pages/Staking/Overview/components/Actions/Actions.tsx, src/renderer/shared/ui/Dropdowns/DropdownButton/DropdownButton.stories.tsx, src/renderer/shared/ui/Dropdowns/DropdownButton/DropdownButton.test.tsx, src/renderer/shared/ui/Dropdowns/DropdownButton/DropdownButton.tsx
- Fixed long names for wallets
- Correct icons for "add wallet"
=> Fix: Long names

src/renderer/components/common/Scanning/ScanSingleframeQr.tsx, src/renderer/entities/transaction/ui/DepositWithLabel/DepositWithLabel.tsx, src/renderer/pages/Operations/components/modals/RejectTx.tsx, src/renderer/widgets/SendAssetModal/ui/components/ActionSteps/Confirmation.tsx
- styles fixed
- added back icon for non-xcm transfers
=> Fix: transfer wallets problems  

src/renderer/features/wallets/WalletSelect/ui/WalletPanel.tsx, src/renderer/features/wallets/WalletSelect/ui/WalletSelect.tsx, src/renderer/pages/Operations/components/Details.tsx, src/renderer/widgets/Layout/ui/MainLayout.tsx
- Removed extra divider for multisig staking operations confrimation screen
- Close wallet select after wallet selected
- Fixed wallet select z-index
=> Fix: wallet select UI bugs

src/renderer/components/common/QrCode/QrReader/QrReaderWrapper.tsx, src/renderer/pages/Operations/components/Details.tsx, src/renderer/pages/Operations/components/OperationCardDetails.tsx, src/renderer/shared/ui/Countdown/Countdown.tsx
- Updated countdown z-index
- Fixed validators modal on operation details
- Changed field order for operation confirmation page
=> Fix: validators list, qr timer and confirmation fields order

src/renderer/features/operation/sign/ui/WalletConnect/WalletConnect.tsx
Fixed wallet connect qr timer to match vault timer
https://app.clickup.com/t/86930aqtt
=> Fix: wc qr timer display

src/renderer/features/wallets/WalletSelect/ui/WalletPanel.tsx, src/renderer/widgets/CreateWallet/ui/MultisigAccount/components/ConfirmSignatories.tsx, src/renderer/widgets/CreateWallet/ui/MultisigAccount/components/SelectSignatories.tsx
fix: wallet connect icon
fix: design update
=> fix: wallet connect icon

src/renderer/assets/chains/chains.json, src/renderer/assets/chains/chains_dev.json
That PR adds multisig parameter to the options list.
Added by script:
```python
import json
from collections import OrderedDict
networks_with_multisig = ["Acala", "Aleph Zero", "Altair", "Astar", "Basilisk", 
"Bifrost Kusama", "Bifrost Polkadot", "Centrifuge Parachain", 
"Enjin", "HydraDX", "Imbue", "Interlay", "Jur", "Karura", 
"Khala", "Kintsugi", "Kusama", "Kusama Bridge Hub", 
"Parallel", "Parallel Heiko", "Pendulum", "Phala", 
"Picasso", "Polkadot", "Polkadot Bridge Hub", "Shiden", 
"Westend", "Zeitgeist"]
with open('src/renderer/assets/chains/chains.json', 'r') as f:
data = json.load(f, object_pairs_hook=OrderedDict)
for chain in data:
if chain['name'] in networks_with_multisig:
if 'options' in chain:
if 'multisig' not in chain['options']:
chain['options'].append('multisig')
else: …
```
=> feat: add multisig to options

src/renderer/features/navigation/ui/Navigation.tsx
Zero shouldn't shown for Operations counter.
https://app.clickup.com/t/869308xyb
=> Fix: operations shows zero

src/renderer/features/operation/sign/model/wallet-connect-sign-model.ts, src/renderer/features/operation/sign/ui/WalletConnect/WalletConnect.tsx, src/renderer/widgets/WalletDetails/model/wc-details-model.ts
* move reject checking to sign model
=> Fix: reject signing

src/renderer/features/operation/sign/model/wallet-connect-sign-model.ts, src/renderer/features/operation/sign/ui/WalletConnect/WalletConnect.tsx
* fix: correct check and save connection on reconnect from signing
=> Fix: correct check connection

src/renderer/shared/api/storage/migration/migration-2.ts
=> fix: multisig accounts migration

src/renderer/pages/Assets/AssetsList/components/SelectShardModal/SelectShardModal.tsx, src/renderer/shared/api/storage/migration/migration-2.ts
- Fix migration for multishard accounts
=> Fix: Multishard migration

src/renderer/app/providers/context/NetworkContext/NetworkContext.test.tsx, src/renderer/app/providers/context/NetworkContext/NetworkContext.tsx
fix: use active accounts for balance subscription
=> fix: use active accounts for balance subscription

src/renderer/pages/Staking/Operations/components/Confirmation/Confirmation.tsx, src/renderer/widgets/SendAssetModal/ui/components/ActionSteps/Confirmation.tsx
* use signer for multisig account to check correct button title
=> fix: correct sign button on staking

src/renderer/entities/staking/ui/ValidatorsModal/ValidatorsModal.tsx, src/renderer/entities/staking/ui/ValidatorsTable/ValidatorsTable.tsx, src/renderer/pages/Operations/components/ActionSteps/Confirmation.tsx, src/renderer/pages/Operations/components/Details.tsx
- Updated validotors table scroll and fixed validators table on multisig confirmation screen
- Fixed padding for xcm fee
=> Fix: validators table scroll fix and confirmation page padding

src/renderer/app/providers/context/NetworkContext/NetworkContext.tsx
* fix: remove unnecessary balance subscribe when connect to network
=> fix: remove unnecessary balance subscribe

package.json, pnpm-lock.yaml, src/renderer/app/index.tsx, src/renderer/app/providers/context/NetworkContext/NetworkContext.tsx, src/renderer/entities/asset/lib/balanceService.ts, src/renderer/entities/asset/lib/common/types.ts, src/renderer/entities/network/lib/networkService.ts, src/renderer/features/operation/init/index.ts, src/renderer/features/operation/init/ui/__tests__/OperationHeader.test.tsx, src/renderer/pages/Staking/Operations/Bond/InitOperation/InitOperation.tsx, src/renderer/pages/Staking/Operations/Redeem/InitOperation/InitOperation.tsx, src/renderer/pages/Staking/Operations/Restake/InitOperation/InitOperation.tsx, src/renderer/pages/Staking/Operations/StakeMore/InitOperation/InitOperation.tsx, src/renderer/pages/Staking/Operations/Unstake/InitOperation/InitOperation.tsx, src/renderer/services/subscription/__tests__/subscriptionService.test.ts, src/renderer/services/subscription/common/types.ts, src/renderer/services/subscription/subscriptionService.ts, src/renderer/shared/api/storage/common/types.ts, src/renderer/shared/api/storage/service/balanceStorage.ts
Improved balance subscription through:
- `bulkPut`
- `async-mutex`
- lesser requests with more data to node
- better `NetworkContext` subscription handling
=> Fix: Balances subscription impovements

src/renderer/entities/asset/lib/balanceService.ts
Get correct `accountId` & `assetId` when balance received
=> Fix: Correct balance assetId

src/renderer/entities/staking/ui/ValidatorsTable/ValidatorsTable.tsx, src/renderer/pages/Staking/Operations/Bond/Bond.tsx, src/renderer/pages/Staking/Operations/components/Confirmation/Confirmation.tsx, src/renderer/pages/Staking/Operations/components/Modals/AccountsModal/AccountsModal.test.tsx, src/renderer/pages/Staking/Operations/components/Modals/AccountsModal/AccountsModal.tsx
- Update Accounts Modal for staking
=> Feat: cleanup staking multishard confirmation

.github/workflows/install-pnpm/action.yaml, app.config.js, package.json, pnpm-lock.yaml, src/main/factories/create.ts, src/main/main.ts, webpack/webpack.renderer.dev.ts
- Updated by hand a few dependencies that was mentioned by `dependabot`
=> Feat: Update dependencies

src/renderer/entities/wallet/lib/__tests__/account-utils.test.ts, src/renderer/entities/wallet/lib/account-utils.ts, src/renderer/shared/core/index.ts, src/renderer/shared/core/types/account.ts
Remove `ShardedAccount` and generate account structure
=> Fix: Removed ShardedAccount

README.md, src/renderer/app/index.css, src/renderer/components/common/OperationTitle/OperationTitle.tsx, src/renderer/pages/Staking/Overview/components/Actions/Actions.tsx, src/renderer/pages/Staking/Overview/components/NetworkInfo/NetworkInfo.tsx, src/renderer/pages/Staking/Overview/components/NominatorsList/NominatorsList.tsx
- Added `font-smooth`
- Fixed `DropdownButton` height
- Fixed height of staking row
- Fixed staking total balance `font-manrope`
- Fixed modal title
=> Fix: Font-smooth and ui

src/renderer/pages/Onboarding/Vault/Vault.tsx
* check ExportAddrV2 code doesn't contain derived keys, otherwise show add multishard wallet screen
=> fix: allow only single account for dynamic derivations

src/renderer/components/common/QrCode/QrGenerator/common/utils.ts, src/renderer/features/wallets/DerivationsAddressModal/lib/utils.ts, src/renderer/features/wallets/DerivationsAddressModal/ui/DerivationsAddressModal.tsx, src/renderer/pages/Assets/AssetsList/components/SelectShardModal/SelectShardModal.tsx
- Added `cryptoTypeToMultisignerIndex` adapter function to map `CryptoType` enum indexes to values used by `DYNAMIC_DERIVATIONS_REQUEST`
- Fixed padding for `DerivationsAddressModal`
- Fixed address prefix for root key in `SelectShardModal`
=> Fix: CryptoType indexes

SECURITY.md
This PR closes the issue #1036
=> feat: added security policy

src/renderer/features/wallets/KeyConstructor/model/__tests__/constructor-model.test.ts, src/renderer/features/wallets/KeyConstructor/model/constructor-model.ts, src/renderer/features/wallets/KeyConstructor/ui/KeysList.tsx
- Added tests
- Use store variable to determine whether to show empty screen
=> Fix: Remove dd key

src/renderer/widgets/CreateWallet/ui/MultisigAccount/components/SelectSignatories.tsx
Updated what tootlip message shown for signatory's list disabled wallet
=> Feat: multisig signatory tooltip update

src/renderer/entities/wallet/index.ts, src/renderer/entities/wallet/lib/constants.ts, src/renderer/features/wallets/ImportKeys/lib/import-keys-utils.ts, src/renderer/features/wallets/ImportKeys/lib/types.ts, src/renderer/features/wallets/KeyConstructor/model/constructor-model.ts
- Fill imported derivations names based on type
=> Fix: import derivations names

src/renderer/components/common/QrCode/QrGenerator/QrTextGenerator.tsx, src/renderer/components/common/QrCode/QrGenerator/QrTxGenerator.test.tsx, src/renderer/components/common/QrCode/QrGenerator/QrTxGenerator.tsx, src/renderer/components/common/QrCode/QrGenerator/common/utils.test.ts, src/renderer/components/common/QrCode/QrGenerator/common/utils.ts, src/renderer/components/common/Scanning/ScanSingleframeQr.tsx, src/renderer/components/common/index.ts, src/renderer/entities/signatory/lib/utils.ts, src/renderer/entities/wallet/lib/account-utils.ts, src/renderer/entities/wallet/lib/wallet-utils.ts, src/renderer/entities/wallet/ui/Cards/WalletCardLg/WalletCardLg.tsx, src/renderer/entities/wallet/ui/Cards/WalletCardMd/WalletCardMd.tsx, src/renderer/entities/walletConnect/lib/utils.ts, src/renderer/entities/walletConnect/model/wallet-connect-model.ts, src/renderer/features/operation/init/ui/OperationHeader.tsx, src/renderer/features/operation/sign/index.ts, src/renderer/features/operation/sign/model/index.ts, src/renderer/features/operation/sign/model/types.ts, src/renderer/features/operation/sign/ui/Signing/Signing.tsx, src/renderer/features/operation/sign/ui/VaultSigning/VaultSigning.tsx, src/renderer/features/operation/sign/ui/WalletConnect/WalletConnect.tsx, src/renderer/features/wallets/WalletSelect/model/wallet-select-model.ts, src/renderer/pages/Assets/AssetsList/AssetsList.tsx, src/renderer/pages/Operations/components/LogModal.tsx, src/renderer/pages/Staking/Overview/Overview.tsx, src/renderer/pages/Staking/Overview/common/types.ts, src/renderer/shared/core/index.ts, src/renderer/shared/core/types/wallet.ts, src/renderer/widgets/ReceiveAssetModal/ui/ReceiveAssetModal.tsx
- Use `signingType` of active signatory not active wallet for Vault signing
=> Fix: Signatory signing type

src/renderer/features/wallets/DerivationsAddressModal/ui/DerivationsAddressModal.tsx, src/renderer/features/wallets/KeyConstructor/model/__tests__/constructor-model.test.ts, src/renderer/features/wallets/KeyConstructor/model/constructor-model.ts, src/renderer/features/wallets/KeyConstructor/ui/KeyForm.tsx, src/renderer/features/wallets/KeyConstructor/ui/KeysList.tsx, src/renderer/features/wallets/KeyConstructor/ui/ShardInfoPopover.tsx, src/renderer/pages/Onboarding/Vault/ManageDynamicDerivations/ManageDynamicDerivations.tsx, src/renderer/pages/Onboarding/Vault/ManageDynamicDerivations/VaultInfoPopover.tsx, src/renderer/pages/Onboarding/Vault/ManageDynamicDerivations/model/__tests__/manage-dynamic-derivations-model.test.ts, src/renderer/pages/Onboarding/Vault/ManageDynamicDerivations/model/manage-dynamic-derivations-model.ts, src/renderer/pages/Staking/Overview/Overview.tsx, src/renderer/pages/Staking/Overview/components/NominatorsList/NominatorItem/NominatorItem.tsx, src/renderer/pages/Staking/Overview/components/NominatorsList/NominatorsList.tsx, src/renderer/shared/api/translation/locales/en.json, src/renderer/shared/lib/utils/arrays.ts
Fixed:
- Trim long names in constructor
- Reset errors
- Don't reset network after form submission
- Popover positioned in center
- "Edit keys" button text
- More tests
=> Fix: Dynamic derivation fixes

src/renderer/features/wallets/ImportKeys/lib/import-keys-utils.ts
Check for duplicated path during derivations import
=> Fix: Check for duplicated path during derivations import

src/renderer/pages/Staking/Overview/Overview.tsx
- Allow staking with root shard for legacy multishards
- Fix staking for singleshard
=> Fix: staking shards

src/renderer/widgets/ReceiveAssetModal/ui/ReceiveAssetModal.tsx
Hide root account for Polkadot Vault in receive modal selector
Show shards addresses
=> Fix: Receive selector

src/renderer/entities/asset/ui/AssetCard/AssetCard.tsx, src/renderer/pages/Assets/AssetsList/AssetsList.tsx, src/renderer/pages/Assets/AssetsList/components/NetworkAssets/NetworkAssets.tsx, src/renderer/widgets/SendAssetModal/ui/SendAssetModal.tsx
Close send asset modal if active wallet is WOW
=> Fix: WOW can be used in transfer immediately after switch wallet

src/renderer/pages/Onboarding/Vault/ManageVault/ManageVault.tsx, src/renderer/shared/api/translation/locales/en.json, src/renderer/shared/ui/Alert/Alert.tsx, src/renderer/widgets/WalletDetails/ui/VaultWalletDetails.tsx
- Public key text and value
- Alert full width
=> Fix: Key alert

src/renderer/entities/balance/lib/balanceSubscriptionService.ts, src/renderer/entities/balance/lib/common/constants.ts, src/renderer/entities/balance/model/balance-model.ts, src/renderer/entities/network/model/network-model.ts, src/renderer/features/balances/common/constants.ts, src/renderer/features/balances/model/balance-subscription-model.ts, src/renderer/pages/Assets/AssetsList/components/NetworkAssets/NetworkAssets.tsx
`Network` & `Balances` optimization
=> fix: balances and networks refactoring

src/renderer/features/operation/init/ui/OperationHeader.tsx, src/renderer/widgets/SendAssetModal/ui/common/utils.tsx, src/renderer/widgets/SendAssetModal/ui/components/ActionSteps/InitOperation.tsx
Removed ability to select root account for polkadot vault and changed display name for shards
=> Feat: Update shard selector on the Transfer page for the Polkadot Vault wallet

src/renderer/app/index.tsx, src/renderer/entities/asset/ui/AssetCard/AssetCard.tsx, src/renderer/entities/balance/model/balance-model.ts, src/renderer/features/balances/model/balance-subscription-model.ts, src/renderer/features/wallets/ShardSelectorModal/model/__tests__/shards-model.test.ts
- Batch update balances for chain
- Removed zero balance filter
=> Fix: Zero balances

src/renderer/features/wallets/ShardSelectorModal/lib/shards-utils.ts, src/renderer/features/wallets/ShardSelectorModal/model/shards-model.ts
- Fixed number of selected shards
- Fixed semichecked for "All accounts"
=> Fix: Number of selected for multishard

src/renderer/pages/Assets/Assets/components/AssetsList/AssetsList.tsx
=> Fix: Watch wallet on asset list

src/renderer/app/providers/context/MatrixContext/MatrixContext.tsx
* use accounts ref for events handlers
=> fix: missed data from matrix event

.storybook/preview.js, src/renderer/entities/proxy/index.ts, src/renderer/entities/proxy/lib/constants.ts, src/renderer/entities/proxy/lib/types.ts, src/renderer/entities/proxy/ui/ProxyAccount/ProxyAccount.stories.tsx, src/renderer/entities/proxy/ui/ProxyAccount/ProxyAccount.test.tsx, src/renderer/entities/proxy/ui/ProxyAccount/ProxyAccount.tsx, src/renderer/shared/api/translation/locales/en.json
- Added `ProxyType` enum and `ProxyTypeName` conts
- Added ProxyAccount UI component
- Storybook fix (but it's still not working)
***
=> Feat: UI componnet for proxy account

src/renderer/entities/network/lib/common/utils.ts, src/renderer/entities/network/model/network-model.ts
* use create instead of update when we try to update default connection state
=> fix: network update

src/renderer/entities/network/lib/common/constants.ts, src/renderer/shared/api/xcm/common/types.ts, src/renderer/shared/api/xcm/xcmService.ts, src/renderer/shared/core/index.ts, src/renderer/shared/core/types/substrate.ts, src/renderer/shared/lib/utils/__tests__/substrate.test.ts, src/renderer/shared/lib/utils/constants.ts, src/renderer/shared/lib/utils/substrate.ts, src/renderer/widgets/SendAssetModal/model/send-asset.ts, src/renderer/widgets/SendAssetModal/ui/components/ActionSteps/InitOperation.tsx
* get types for xcm versioned from call arguments
=> fix: bifrost xcm types 

src/renderer/entities/balance/model/balance-model.ts, src/renderer/entities/wallet/model/wallet-model.ts, src/renderer/features/proxies/model/proxies-model.ts, src/renderer/features/proxies/workers/proxy-worker.ts, src/renderer/features/wallets/ForgetWallet/model/__tests__/forget-wallet-model.test.ts, src/renderer/features/wallets/ForgetWallet/model/forget-wallet-model.ts, src/renderer/widgets/WalletDetails/model/wc-details-model.ts
Receive proxiedes accounts from proxy service which was deleted. Remove it with related wallets and balances.
=> feat: remove proxied wallets

tests/system/matrix/matrix.auth.system.test.tsx, tests/system/pages/_elements/LoginPageElements.ts, tests/system/pages/assetsPage/WatchOnlyPageAssetsPage.ts
fixed in that PR:
https://github.com/novasamatech/nova-spektr/pull/1367
Tested by run:
https://github.com/novasamatech/nova-spektr/actions/runs/7540516609
results:
https://novasamatech.github.io/spektr-reports/reports/1372/merge/7540516609/2
=> fix: System tests. remove workaround

src/renderer/features/proxies/lib/__tests__/worker-utils.test.ts, src/renderer/features/proxies/lib/worker-utils.ts, src/renderer/features/proxies/workers/proxy-worker.ts
* add check on delay for proxied account creation
=> fix: not create proxied account with non-zero delay

src/renderer/features/proxies/model/__tests__/proxies-model.test.ts, src/renderer/features/proxies/model/proxies-model.ts
* fix add/update proxy groups
* add tests for proxy group
=> fix: add proxy groups

src/main/main.ts, src/renderer/widgets/WalletDetails/ui/components/ProxiesList.tsx
=> Fix: proxy deposit in proxies list

src/renderer/entities/proxy/model/proxy-model.ts, src/renderer/features/proxies/model/proxies-model.ts, src/renderer/features/proxies/workers/proxy-worker.ts
* fix provided data to getProxies function
* fix detecting removed proxies in getProxies
=> fix: add/remove proxies

src/renderer/widgets/WalletDetails/ui/components/NoProxiesAction.tsx
=> fix: proxy description

src/renderer/entities/proxy/lib/__tests__/utils.test.ts, src/renderer/entities/proxy/model/__tests__/proxy-model.test.ts, src/renderer/entities/proxy/model/proxy-model.ts, src/renderer/features/proxies/model/__tests__/proxies-model.test.ts, src/renderer/features/proxies/model/proxies-model.ts, src/renderer/features/proxies/workers/__tests__/proxy-worker.test.ts, src/renderer/features/proxies/workers/proxy-worker.ts, src/renderer/widgets/WalletDetails/model/wallet-provider-model.ts, src/renderer/widgets/WalletDetails/ui/components/ProxiesList.tsx, src/renderer/widgets/WalletDetails/ui/wallets/MultishardWalletDetails.tsx, src/renderer/widgets/WalletDetails/ui/wallets/ProxiedWalletDetails.tsx, src/renderer/widgets/WalletDetails/ui/wallets/VaultWalletDetails.tsx, src/renderer/widgets/WalletDetails/ui/wallets/WalletConnectDetails.tsx
* proxy creation through db
* collect proxies for newly created proxied account
=> fix:  proxy creation through db

src/renderer/entities/proxy/model/proxy-model.ts, src/renderer/features/proxies/lib/__tests__/proxies-utils.test.ts, src/renderer/features/proxies/lib/proxies-utils.ts, src/renderer/features/proxies/model/proxies-model.ts
* remove useless code 
* don't search proxied accounts for proxied accounts
=> fix: remove proxies

src/renderer/entities/proxy/ui/ProxyPopover.tsx, src/renderer/entities/transaction/ui/DepositWithLabel/DepositWithLabel.tsx, src/renderer/features/operation/init/ui/OperationFooter.tsx, src/renderer/features/wallets/KeyConstructor/ui/ShardInfoPopover.tsx, src/renderer/features/wallets/WalletSelect/ui/ProxiedTooltip.tsx, src/renderer/pages/Onboarding/Vault/ManageVault/VaultInfoPopover.tsx, src/renderer/pages/Staking/Operations/components/StakingPopover/StakingPopover.tsx, src/renderer/pages/Staking/Overview/components/NominatorsList/ShardedList/ShardedList.tsx, src/renderer/shared/ui/Popovers/Popover/Popover.tsx, src/renderer/shared/ui/Popovers/Tooltip/Tooltip.css, src/renderer/shared/ui/Popovers/Tooltip/Tooltip.tsx, src/renderer/shared/ui/Popovers/common/types.ts, src/renderer/widgets/CreateWallet/ui/MultisigWallet/components/SelectSignatories.tsx, src/renderer/widgets/MatrixModal/ui/MatrixInfoPopover.tsx, src/renderer/widgets/WalletDetails/ui/components/NoProxiesAction.tsx
=> Fix: Popover styles

src/renderer/entities/proxy/model/proxy-model.ts, src/renderer/widgets/CreateWallet/ui/MultisigWallet/components/WalletForm.tsx
* fix: proxies in details
* fix: add multisig when proxied already exists
=> fix: proxies in details

src/renderer/features/notifications/NotificationsList/model/__tests__/notification-list-model.test.ts, src/renderer/features/notifications/NotificationsList/model/notification-list-model.ts
Fixed notification sort inside groups - the most recent at top
=> Fix: Notifications sort

src/renderer/entities/wallet/ui/Cards/WalletCardLg.tsx, src/renderer/entities/wallet/ui/Cards/WalletCardMd.tsx, src/renderer/entities/wallet/ui/Cards/WalletCardSm.tsx, src/renderer/features/notifications/NotificationsList/ui/notifies/ProxyCreatedNotification.tsx, src/renderer/features/notifications/NotificationsList/ui/notifies/ProxyRemovedNotification.tsx, src/renderer/shared/api/translation/locales/en.json, src/renderer/widgets/WalletDetails/ui/wallets/ProxiedWalletDetails.tsx
* fix wallet name wrapping for notifications
* truncate long wallet names
=> fix: name wrapping

src/renderer/app/App.tsx
* check that user already have wallets and don't need to redirect to assets
=> fix: don't switch to assets after add proxied

src/renderer/entities/wallet/lib/account-utils.ts, src/renderer/pages/Assets/Assets/components/AssetsList/AssetsList.tsx
* check is chain id match for active accounts on assets page
=> fix: show assets for available chains

src/renderer/widgets/RemoveProxy/ui/RemoveProxy.tsx, src/renderer/widgets/RemoveProxy/ui/Submit.tsx
- Removed proxied wallet notification from remove proxy flow
=> Fix: remove proxy pending state

src/renderer/pages/Assets/Assets/model/__tests__/assets-model.test.ts, src/renderer/pages/Assets/Assets/model/assets-model.ts
- Hide zero balance by default
- Tests
=> Fix: Hide zero balance by default

src/renderer/features/wallets/KeyConstructor/ui/KeyForm.tsx
* fix: remove staking and governance from default derivation key types
=> fix: remove staking and governance from default derivation key types

src/renderer/widgets/WalletDetails/model/wallet-provider-model.ts
- changed `$canCreateProxy` store
=> Fix: Revoke access for proxied accounts should not be accessed

src/renderer/app/index.tsx, src/renderer/entities/transaction/lib/__tests__/callDataDecoder.test.ts, src/renderer/entities/transaction/lib/__tests__/transactionIcon.test.ts, src/renderer/entities/transaction/lib/extrinsicService.ts, src/renderer/entities/transaction/lib/mock/extrinsicService.mock.ts
=> Fix: Use transferKeepAlive instead of transferAllowDeath

src/renderer/features/wallets/KeyConstructor/ui/ShardInfoPopover.tsx, src/renderer/shared/ui/Popovers/Popover/Popover.tsx
Removed focus from info icon in constructor form
=> Fix: Remove focus from info

src/renderer/widgets/CreateWallet/ui/MultisigWallet/components/ConfirmSignatories.tsx, src/renderer/widgets/CreateWallet/ui/MultisigWallet/components/SelectSignatories.tsx
- Fixed overflow for wallets and contacts tabs in create multisig modal
=> Fix: create multisig signatories list overflow

src/renderer/shared/config/chains/chains.json, src/renderer/shared/config/chains/chains_dev.json
=> fix: remove staking for polkadex/ternoa

src/renderer/entities/operation/ui/SignButton.tsx, src/renderer/pages/Operations/components/ActionSteps/Confirmation.tsx, src/renderer/shared/api/translation/locales/en.json
closes https://github.com/novasamatech/nova-spektr/issues/1397
I went for the second solution from my comment https://github.com/novasamatech/nova-spektr/issues/1397#issuecomment-1931928078 because I thought it would be cleaner.
=> fix: Allow unkown wallet type

src/renderer/features/wallets/KeyConstructor/model/__tests__/constructor-model.test.ts, src/renderer/features/wallets/KeyConstructor/model/constructor-model.ts, src/renderer/features/wallets/KeyConstructor/ui/KeyForm.tsx, src/renderer/features/wallets/KeyConstructor/ui/KeysList.tsx, src/renderer/shared/api/translation/locales/en.json
- Added Main Account to key type dropdown on DD edit keys screen
- Show keys with type main on DD edit keys screen
=> Fix: Add main key type to key type dropdon for DD

src/renderer/features/wallets/ImportKeys/lib/__tests__/import-keys-model.test.ts, src/renderer/features/wallets/ImportKeys/lib/import-keys-utils.ts, src/renderer/features/wallets/ImportKeys/lib/mocks/import-keys-model.mock.ts, src/renderer/features/wallets/ImportKeys/model/import-keys-model.ts, src/renderer/features/wallets/KeyConstructor/model/__tests__/constructor-model.test.ts, src/renderer/features/wallets/KeyConstructor/model/__tests__/mocks/constructor-mock.ts, src/renderer/features/wallets/KeyConstructor/model/constructor-model.ts
- Validate derivation path to be unique only with keys in same network
=> Fix: updated unique derivation path validation

src/renderer/app/providers/context/MatrixContext/MatrixContext.tsx, src/renderer/pages/Operations/components/ActionSteps/Submit.tsx, src/renderer/pages/Staking/Operations/components/Submit/Submit.tsx, src/renderer/shared/core/types/account.ts, src/renderer/widgets/CreateWallet/model/create-multisig-wallet-mode.ts, src/renderer/widgets/RemoveProxy/ui/Submit.tsx, src/renderer/widgets/SendAssetModal/ui/components/ActionSteps/Submit.tsx
* add checks for matrix room id exists
* skip create matrix room if all accounts is controlled by user
=> fix: skip matrix room creation for my accounts

src/main/main.ts, src/renderer/features/proxies/workers/proxy-worker.ts
* call provider.connect only for light client connection
=> fix: connect to ws in worker

src/renderer/widgets/CreateWallet/ui/MultisigWallet/MultisigWallet.tsx, src/renderer/widgets/CreateWallet/ui/MultisigWallet/SelectMultisigWalletType.tsx
* use correct nesting for modal on multisig creation
=> fix: matrix modal on multisig

src/renderer/entities/wallet/ui/ContactItem/ContactItem.tsx, src/renderer/shared/api/translation/locales/en.json, src/renderer/widgets/CreateWallet/model/create-multisig-wallet-model.ts, src/renderer/widgets/CreateWallet/ui/MultisigWallet/SelectMultisigWalletType.tsx, src/renderer/widgets/CreateWallet/ui/MultisigWallet/SingleChainMultisigWallet.tsx, src/renderer/widgets/CreateWallet/ui/MultisigWallet/components/ConfirmSignatories.tsx, src/renderer/widgets/CreateWallet/ui/MultisigWallet/components/SelectAccountSignatories.tsx, src/renderer/widgets/CreateWallet/ui/MultisigWallet/components/WalletForm.tsx, src/renderer/widgets/WalletDetails/ui/wallets/MultisigWalletDetails.tsx
closes #1461 #1463 #1464 #1465 
* show base accounts on single chain multisig creation
* show accounts on singlechain multisig wallet details
* exclude multisig accounts from multisig creation
=> fix: single chain multisig feedback

src/renderer/widgets/CreateWallet/model/create-multisig-wallet-model.ts, src/renderer/widgets/CreateWallet/ui/MultisigWallet/components/ConfirmSignatories.tsx, src/renderer/widgets/CreateWallet/ui/MultisigWallet/components/SelectAccountSignatories.tsx, src/renderer/widgets/CreateWallet/ui/MultisigWallet/components/SelectSignatories.tsx
* exclude wow accounts from multisig creation
* fix accounts list
=> fix: exclude wow accounts from multisig creation

src/renderer/app/providers/context/MatrixContext/MatrixContext.tsx, src/renderer/features/matrix/MatrixAutoLogin/lib/matrix-autologin-utils.ts, src/renderer/features/matrix/MatrixAutoLogin/lib/types.ts, src/renderer/features/matrix/MatrixAutoLogin/model/__tests__/matrix-autologin-model.test.ts, src/renderer/features/matrix/MatrixAutoLogin/model/matrix-autologin-model.ts, src/renderer/features/matrix/MatrixAutoLogin/ui/MatrixAutoLogin.tsx, src/renderer/features/matrix/MatrixLogin/ui/LoginForm.tsx, webpack/webpack.renderer.dev.ts, webpack/webpack.renderer.stage.ts
- Try to login with token if token exists and cache failed
- Use $loginStatus in MatrixLogin form
- Fixed stage dev for electron
- Tests
closes #1460
=> Fix: Duplicated SSO login 

electron-builder.js, src/main/factories/protocol.ts, src/main/factories/window.ts, src/main/index.ts, src/renderer/features/matrix/MatrixLogin/ui/LoginForm.tsx, src/renderer/shared/ui/Popovers/Popover/Popover.test.tsx
- Reverted custom electron scheme to default `file://`
closes #1462
=> Fix: Revert scheme

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/workflows/build_stage.yaml, src/renderer/entities/operation/ui/SignButton.tsx, src/renderer/features/wallets/ForgetWallet/index.ts, src/renderer/features/wallets/ForgetWallet/model/__tests__/forget-wallet-model.test.ts, src/renderer/features/wallets/ForgetWallet/model/forget-wallet-model.ts, src/renderer/pages/Operations/components/ActionSteps/Confirmation.tsx, src/renderer/shared/api/translation/locales/en.json, src/renderer/widgets/WalletDetails/ui/components/WalletConnectAccounts.tsx, src/renderer/widgets/WalletDetails/ui/wallets/WalletConnectDetails.tsx
* fix conflicts between dev and baseline
=> fix: merge conflicts 

src/renderer/widgets/CreateWallet/ui/MultisigWallet/components/WalletForm.tsx
=> fix: disable chain selector on confirm step

package.json, src/main/factories/window.ts, src/main/shared/constants/environment.ts, webpack/webpack.main.prod.internal.ts, webpack/webpack.renderer.prod.internal.ts
- use `https://localhost:3000` origin in `dev`
- use `file://` in `prod`
- removed `FORCE_ELECTRON`, not needed anymore
closes #1489
=> Fix: Localhost scheme

src/renderer/widgets/WalletDetails/model/wallet-provider-model.ts, src/renderer/widgets/WalletDetails/ui/components/WalletDetailsProvider.tsx, src/renderer/widgets/WalletDetails/ui/wallets/MultisigWalletDetails.tsx
closes #1461 
* filter signatory accounts by existed accounts
=> fix: signatories for multisig

src/renderer/entities/network/lib/network-utils.ts, src/renderer/entities/transaction/ui/QrCode/QrGenerator/common/utils.ts, src/renderer/entities/transaction/ui/QrCode/QrReader/QrReader.tsx, src/renderer/entities/wallet/lib/__tests__/account-utils.test.ts, src/renderer/entities/wallet/lib/account-utils.ts, src/renderer/entities/wallet/ui/AccountAddress/AccountAddress.tsx, src/renderer/entities/wallet/ui/Cards/DerivedAccount.tsx, src/renderer/features/balances/model/balance-subscription-model.ts, src/renderer/features/wallets/DerivationsAddressModal/ui/DdKeyQrReader.tsx, src/renderer/features/wallets/KeyConstructor/model/constructor-model.ts, src/renderer/pages/Onboarding/Vault/KeyQrReader/KeyQrReader.tsx, src/renderer/pages/Onboarding/Vault/ManageSingleshard/ManageSingleshard.tsx, src/renderer/pages/Onboarding/Vault/ManageVault/model/manage-vault-model.ts, src/renderer/pages/Onboarding/WatchOnly/WatchOnly.tsx, src/renderer/shared/api/translation/locales/en.json, src/renderer/shared/core/types/chain.ts, src/renderer/shared/lib/utils/address.ts, src/renderer/shared/lib/utils/constants.ts, src/renderer/shared/lib/utils/strings.ts, src/renderer/widgets/CreateWallet/model/create-multisig-wallet-model.ts, src/renderer/widgets/CreateWallet/ui/MultisigWallet/components/WalletForm.tsx
* create evm accounts for watch only/singleshard/multishard/vault accounts 
* check crypto type for balance subscription
=> feat: create accounts in evm chains

src/renderer/widgets/CreateWallet/model/create-multisig-wallet-model.ts
=> fix: matrix room create condition
